git clone https://github.com/governify/bluejay-infrastructure
git clone https://github.com/governify/render
git clone https://github.com/governify/assets-manager
git clone https://github.com/governify/reporter
git clone https://github.com/governify/registry
git clone https://github.com/governify/dashboard
git clone https://github.com/governify/assets-manager
git clone https://github.com/governify/director
git clone https://github.com/governify/collector-events
git clone https://github.com/governify/scope-manager
git clone https://github.com/governify/join-bluejay
git clone https://github.com/governify/galibo-logs
git clone https://github.com/governify/collector-dynamic